CREATE TABLE invoices(
invoice_id SERIAL PRIMARY KEY,
pesel CHAR(11) REFERENCES customers(pesel),
amount DECIMAL CHECK(LENGTH(CAST(amount AS TEXT))<=8 AND SUBSTRING(SUBSTRING(CAST(amount AS TEXT),LENGTH(CAST(amount AS TEXT))-2,LENGTH(CAST(amount AS TEXT))-2),1,1)='.' AND SUBSTRING(CAST(amount AS TEXT),LENGTH(CAST(amount AS TEXT)),LENGTH(CAST(amount AS TEXT)))!='0' AND SUBSTRING(CAST(amount AS TEXT),LENGTH(CAST(amount AS TEXT))-1,LENGTH(CAST(amount AS TEXT))-1)!='0'));